### PR TITLE
Signage solution

### PR DESCRIPTION
**Pull request by noFlowWater**
I would like to incorporate this guide post about the results of our capstone design project into the website. 
Please review our [2023-12-21-face-certificate-kiosk-using-webos.md](https://github.com/noFlowWater/website/blob/signage_solution/content/en/samples/posts/2023-12-21-face-certification-kiosk-using-webos.md) and [other related files.](https://github.com/webosose/website/pull/13/files)

> Note: [our project repository](https://github.com/noFlowWater/signage_solution?tab=readme-ov-file)

> This pull request is a copy of #11.

### CODE REVIEW

**Review by Heeam-Shin — APPROVED** [review]

**Comment by Heeam-Shin** [comment]
@noFlowWater,

This pull request has been merged successfully. You can check the [published post](https://www.webosose.org/samples/2023/12/21/facial-recognition-kiosk-using-webos/).

**Comment by noFlowWater** [comment]
@Heeam-Shin 
Thank you for letting me know! 
I've checked it out, but as you can see in the screenshot, the image isn't displaying properly.

image
스크린샷 2023-12-21 오후 3 32 27

**Comment by Heeam-Shin** [comment]
@noFlowWater ,

Thank you for your report. I've fixed the image path.

**Comment by Heeam-Shin** [comment]
@noFlowWater,

Could you change one image? https://github.com/noFlowWater/signage_solution/assets/112642604/248f7596-9c3f-4de7-a14a-638547a09816

I recommend changing the description of the image to English. Refer to the sample text below.

----

Kiosk API Server
- User-based menu recommendation algorithm
- Support kiosk APIs

User Authentication Server
- User registration (Training a face recognition model)
- User detection/authentication

Database
- Store User information: Trained facial recognition models, allergy information, and menu order history
- Menu information: Photos and allergy information for each menu

**Comment by noFlowWater** [comment]
@Heeam-Shin 

I got it.
Based on the text you gave me, I will replace it with an English-modified image and let you know.

If there's anything else to fix, I'll reflect it!

**Comment by noFlowWater** [comment]
> @noFlowWater,
> 
> Could you change one image? https://github.com/noFlowWater/signage_solution/assets/112642604/248f7596-9c3f-4de7-a14a-638547a09816
> 
> I recommend changing the description of the image to English. Refer to the sample text below.
> 
> Kiosk API Server
> 
> * User-based menu recommendation algorithm
> * Support kiosk APIs
> 
> User Authentication Server
> 
> * User registration (Training a face recognition model)
> * User detection/authentication
> 
> Database
> 
> * Store User information: Trained facial recognition models, allergy information, and menu order history
> * Menu information: Photos and allergy information for each menu

@Heeam-Shin 

I've finished modifying the image!
Please replace it with the next image url.

https://github.com/noFlowWater/signage_solution/assets/112642604/7e142fd6-f8c1-4aeb-afb7-12106b938a5f

Or please let me know if you have any request for modification

**Comment by Heeam-Shin** [comment]
@noFlowWater,

I update the image URL. Thanks! :)

**Pull request merged**
