### PR TITLE
ADD : facial-recognition-based-kiosks and thumbnail

### PR DESCRIPTION
**Pull request by baegopababjo**

### CODE REVIEW

**Comment by Heeam-Shin** [comment]
Hi @baegopababjo, thanks for your contribution.

- Your pull request (PR) is in progress. So, I changed its status to 'Draft,' which means this PR is under construction.  If you finish your job, please click 'Ready for review', and then I'll review your PR. (Refer to the ① in the below screenshot.)
- You can preview your website using the 'Details' in this pull request. (Refer to the ② in the below screenshot.)

image

If you have any other questions, feel free to let me know. Thanks! :)

----

### Tips

You can build your own preview on your computer. This makes you edit markdown much easier. 

The steps are as follows:

1.  Go to [Hugo Project](https://github.com/gohugoio/hugo) and download `hugo_extended_xxx` in the **Releases** (Version: [v0.111.1](https://github.com/gohugoio/hugo/releases/tag/v0.111.1))
2. Extract the download `.zip` file.
3. (Recommended) Add `hugo.exe` to environment variables.
4. Go to the root folder of the website, and execute the `hugo` as follows:
     ```
     hugo server -F
     ```
    Then the build process will be started. If you succeed, you can see `Press Ctrl+C to stop` at the bottom.
    ```
    ...
    
    Serving pages from memory
    Running in Fast Render Mode. For full rebuilds on change: hugo server --disableFastRender
    Web Server is available at //localhost:1313/ (bind address 127.0.0.1)
    Press Ctrl+C to stop
    ```
5. Once the build process is done, open any browser and go to `localhost:1313`

**Comment by baegopababjo** [comment]
Hello. As you said, I pressed the 'Ready for review' button, and may I ask when it will be uploaded to the webos samples site?
-----Original Message-----

**Comment by Heeam-Shin** [comment]
@baegopababjo,

I started to review this pull request today. The remaining steps are as follows:

1. **Content review (Current)**
  In this step, I'll follow the steps in the documentation and see if there are any gaps in the explanation. 
  
2. **Request more information**
  I'll ask you for the missing information you found in Step 1. **Then, you need to commit that information on [baegopababjo:main](https://github.com/baegopababjo/website/tree/main).**
  After this step is complete, this pull request will be merged into the `develop` branch, and I'll create a new pull request. 
  The reason is that grammar and documentation structure are related to the style of our website, so it's more efficient to do it myself than to ask for it through a review.
  
3. **Proofreading (in a new pull request)**
  I'll reconstruct the document and fix grammar errors. This step will take a day or two.

4. **Request a final review**
  I'll request you to check the final version of the document. If you agree with the changes, the pull request will be merged and the sample will be posted on the website.
  
If there are no other issues, this sample will be posted on the website next week.

**Comment by baegopababjo** [comment]
Oh I see. Thank you for your reply. Then I will wait until the next step. Thank you.
-----Original Message-----

**Review by Heeam-Shin — CHANGES_REQUESTED** [review]
@baegopababjo, please check the review comments and commit the information.

## Required

- Please describe prerequisites for HW & SW in more detail.
  - In my testing environment, installing `react-scripts` library is needed to run the `npm run build` command. Please double-check to see if there are any other software you used in your project.
  - There is no information about supported camera. If you don't know which camera models are supported, you should at least tell readers which camera you've tested.
  - And it is recommended that you specify all the hardware you used in your tests.
- Please describe how to use the app.
  Some features of the app are very intuitive and easy to use, while others are not. For example, I failed to figure out how to use face recognition feature, which is the main feature of this project.
  You don't need to explain every feature of the app. However, you should provide a description of the core features so that anyone can try it out.
 
## Recommended

- It would be better if you add brief descriptions for each `.py` file in the Code Implementation section. (Code Implementation section will be reorganized to explain one file per one heading -- heading level 3.)
- In the description field (of this GitHub pull request), write what this PR is about.

**Comment by baegopababjo** [comment]
I made a commit after correcting what you said. I would appreciate it if you could check it. Thank you.

-----Original Message-----

**Comment by Heeam-Shin** [comment]
@baegopababjo,

I reviewed your recent commit, and I got some inquiries about it:

- There is no `Url.js` file (even `constants` directory) in the `frontend/register/src` directory. Is that intended?
- Do users need their own server? Are there any other workarounds?
- I still don't know how to use the face recognition feature. What additional steps do you need to take to the source code you've published to GitHub to enable the face recognition feature?

**Comment by baegopababjo** [comment]
There is a git link in the code implementation part, and if you refer to that part, you can find the front end/register/src/constance. Just in case, I'm sending you the git link.
https://github.com/Cheetah-19/Kiosk_KNU

We've added a process that allows you to use facial recognition. Simply put, you must first sign up for membership and then save it to the face information server to log in with your face information. We've also added how to use a personal server.

As a result, I modified the membership registration method and login method and added how to use a private server. Thank you.

-----Original Message-----

**Comment by Heeam-Shin** [comment]
@baegopababjo,

I'll review your commits and get back to you as soon as possible, but I'm also reviewing other PRs, so it may take a while.

**Comment by Heeam-Shin** [comment]
@baegopababjo ,

I followed the steps as what you've written and faced a few errors. Please check the logs below:

For error 1 and error 2, please re-check the step-by-step. Some steps are missing from the current version. Make sure you are clearly providing the following information: **What** commands should be entered and **where**.

### Error 1

Cause: Entering `npm install` in `frontend` is omitted. 

```sh
document@document:~/1-ose/Kiosk_KNU/frontend/register$ npm run build

> register@0.1.0 build
> react-scripts build

Creating an optimized production build...
Failed to compile.

Module not found: Error: Can't resolve 'react-dom' in '/home/document/1-ose/Kiosk_KNU/frontend/register/src'
```

### Error 2

Cause: `bootstrap` module is not installed.

```sh

document@document:~/1-ose/Kiosk_KNU/frontend/kiosk_page$ npm run build

> kiosk_page@0.1.0 build
> react-scripts build

Creating an optimized production build...
Failed to compile.

Module not found: Error: Can't resolve 'bootstrap/dist/css/bootstrap.css' in '/home/document/1-ose/Kiosk_KNU/frontend/kiosk_page/src'
```

### Others

- Korean word '신영재' is hard-coded. Please check the authentication code.
- Once the user starts facial recognition, a very large amount of code is downloaded. Can you change the behavior to download that code in advance?
    - And these codes are **stored outside of the project folder**. Modify to store project-specific code inside the project folder.
- I cannot find the initial sign-up screen.

```sh
Django version 5.0, using settings 'django_react_project.settings'
Starting development server at http://0.0.0.0:1234/
Quit the server with CONTROL-C.  # <- server setting complete ->

# <- Start to recognize face ->
23-12-21 08:30:29 - deploy.prototxt will be downloaded...
Downloading...
From: https://github.com/opencv/opencv/raw/3.4.0/samples/dnn/face_detector/deploy.prototxt
To: /home/document/.deepface/weights/deploy.prototxt
28.1kB [00:00, 42.1MB/s]
23-12-21 08:30:30 - res10_300x300_ssd_iter_140000.caffemodel will be downloaded...
Downloading...
From: https://github.com/opencv/opencv_3rdparty/raw/dnn_samples_face_detector_20170830/res10_300x300_ssd_iter_140000.caffemodel
To: /home/document/.deepface/weights/res10_300x300_ssd_iter_140000.caffemodel
100%|██████████████████████████████████████████████████████████████████| 10.7M/10.7M [00:01<00:00, 5.63MB/s]
23-12-21 08:30:34 - vgg_face_weights.h5 will be downloaded...
Downloading...
From: https://github.com/serengil/deepface_models/releases/download/v1.0/vgg_face_weights.h5
To: /home/document/.deepface/weights/vgg_face_weights.h5
100%|████████████████████████████████████████████████████████████████████| 580M/580M [01:34<00:00, 6.11MB/s]
Received face data from front
신영재입니다: 0.2754466912143686

None
[21/Dec/2023 08:32:13] "POST /login/face/ HTTP/1.1" 200 33
Received face data from front
신영재입니다: 0.26231748873496696

```

**Comment by baegopababjo** [comment]
Error 1 and error 2 can be resolved through the "npm install react-bootstrap bootstrap" command, I added that part.

The '신영재' part was the part we added to check, so we deleted it.

The initial screen for membership registration was originally intended to be accessed through QR code, but due to https certificate problem (SSL) you can proceed with membership registration on your personal pc by performing "npm start" on Kiosk_KNU/frontend/register.

We used the deepface framework for face recognition, and the model is loaded on the Internet when using it for the first time. To modify the process, we need to modify the framework first, so it will take time.


-----Original Message-----

**Comment by Heeam-Shin** [comment]
@baegopababjo ,

I tried again with the current version of the guide, but encountered the following error after entering ` python manage.py runserver 0.0.0.0:'port number'`.

```sh
(20231222test) document@document:~/1-ose/Kiosk_KNU/backend$ python manage.py runserver 0.0.0.0:1234
Watching for file changes with StatReloader
Performing system checks...

2023-12-22 00:52:28.694082: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-12-22 00:52:28.696652: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2023-12-22 00:52:28.728751: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2023-12-22 00:52:28.728768: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2023-12-22 00:52:28.729744: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-12-22 00:52:28.735120: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2023-12-22 00:52:28.735294: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-12-22 00:52:29.397681: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/document/1-ose/Kiosk_KNU/20231222test/lib/python3.11/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/home/document/1-ose/Kiosk_KNU/20231222test/lib/python3.11/site-packages/django/core/management/commands/runserver.py", line 133, in inner_run
    self.check(display_num_errors=True)
  File "/home/document/1-ose/Kiosk_KNU/20231222test/lib/python3.11/site-packages/django/core/management/base.py", line 485, in check
    all_issues = checks.run_checks(
                 ^^^^^^^^^^^^^^^^^^
  File "/home/document/1-ose/Kiosk_KNU/20231222test/lib/python3.11/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/document/1-ose/Kiosk_KNU/20231222test/lib/python3.11/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/document/1-ose/Kiosk_KNU/20231222test/lib/python3.11/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    return check_method()
           ^^^^^^^^^^^^^^
  File "/home/document/1-ose/Kiosk_KNU/20231222test/lib/python3.11/site-packages/django/urls/resolvers.py", line 516, in check
    for pattern in self.url_patterns:
                   ^^^^^^^^^^^^^^^^^
  File "/home/document/1-ose/Kiosk_KNU/20231222test/lib/python3.11/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/home/document/1-ose/Kiosk_KNU/20231222test/lib/python3.11/site-packages/django/urls/resolvers.py", line 735, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
                       ^^^^^^^^^^^^^^^^^^^
  File "/home/document/1-ose/Kiosk_KNU/20231222test/lib/python3.11/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/home/document/1-ose/Kiosk_KNU/20231222test/lib/python3.11/site-packages/django/urls/resolvers.py", line 728, in urlconf_module
    return import_module(self.urlconf_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/document/1-ose/Kiosk_KNU/backend/django_react_project/urls.py", line 29, in <module>
    path('signup/', include('signup.urls')),
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/document/1-ose/Kiosk_KNU/20231222test/lib/python3.11/site-packages/django/urls/conf.py", line 38, in include
    urlconf_module = import_module(urlconf_module)
```

**Comment by Heeam-Shin** [comment]
@baegopababjo,

I was able to commit to the PR branch myself. While I wait for an answer to my question, I will reorganize the document.

**Comment by baegopababjo** [comment]
The environment we test is all Windows PCs, but it ran well, so I didn't know what the problem was, so I kept trying, but I couldn't find a solution. So I proceeded with the rollback. The version also runs well, so I would appreciate it if you could try it again from scratch.
-----Original Message-----

**Comment by baegopababjo** [comment]
The results of the school project must be submitted by the end of December. The results must be listed on the webos site. I'm sure you're busy, but can you check it quickly?


네이버 메일앱에서 보냈습니다.
-----Original Message-----
보낸사람: "Heeam ***@***.***>
받는사람: ***@***.***>
참조: ***@***.***>, ***@***.***>
날짜: 2023. 12. 22 11:54:06
제목: Re: [webosose/website] ADD : facial-recognition-based-kiosks and thumbnail (PR #9)

@baegopababjo,
I was able to commit to the PR branch myself. While I wait for an answer to my question, I will reorganize the document.

**Comment by Heeam-Shin** [comment]
@baegopababjo,

Is it possible to replace the submission with a preview site for the page you're working on? (refer to the below screenshot)
If not, I'll try to upload it (regardless of completion status) by Thursday night (12/28).
image

**Comment by Heeam-Shin** [comment]
@baegopababjo,

- I think there is an error related to ares CLI on Windows.  When I tried `ares-install` on Windows, it failed. But I succeeded on Ubuntu. Could you double-check that you can install the app using the Windows CLI?
- After following the instructions, the server didn't work. 
  - At first, the server didn't respond. When I pressed ctrl+c then the server downloaded the code for deepface. After that, I restarted the server and it worked fine. Do I need to restart the server after setting up port numbers? (or after launching the app?)
- Isn't setting the port number a setting for the app to connect to the server, not for the server to use?

**Comment by baegopababjo** [comment]
Yes, it's not accepted as a preview link, but only officially posted posts on the webos site are accepted. I'll keep revising the feedback. I'd appreciate it if you could post it on the webos official site by Thursday night!


-----Original Message-----
보낸사람: "Heeam ***@***.***>
받는사람: ***@***.***>
참조: ***@***.***>, ***@***.***>
날짜: 2023. 12. 26 15:23:26
제목: Re: [webosose/website] ADD : facial-recognition-based-kiosks and thumbnail (PR #9)

@baegopababjo,
Is it possible to replace the submission with a preview site for the page you're working on? (refer to the below screenshot)
If not, I'll try to upload it (regardless of completion status) by Thursday night (12/28).
image.png (view on web)

**Comment by baegopababjo** [comment]
I think there is an error related to ares CLI on Windows. When I tried ares-install on Windows, it failed. But I succeeded on Ubuntu. Could you double-check that you can install the app using the Windows CLI?
--> Yes, my team member succeeded in the Windows default cmd window. However, other team members showed unstable appearance, sometimes failing, sometimes succeeding, even though they executed the same command as shown in the picture below. Therefore, I modified the technical document to recommend the Linux environment to others.
pr


2. At first, the server didn't respond. When I pressed ctrl+c then the server downloaded the code for deepface. After that, I restarted the server and it worked fine.
--> The face model is downloaded from the server when you first do face recognition. I think it would be better to turn on the server again when I see the terminal and confirm that the face model is downloaded from the server, so I have disclosed it in the document.
Additionally, if there is something like Korean in the file path, you have to change it to English.

3. Isn't setting the port number a setting for the app to connect to the server, not for the server to use?
--> The port number is to connect the app to the server because we write the server ip and port number in url.js.

-----Original Message-----

**Comment by Heeam-Shin** [comment]
@baegopababjo,

After the app recognizes my face once, the face recognition feature does not work again. I need to re-launch the app to re-enable the feature.

Is there any other way to reactivate face recognition?

**Comment by baegopababjo** [comment]
@Heeam-Shin 

It works well on computers such as Windows and Linux environments, but currently, the camera only works once as you said on webos. I tried to solve this problem, but I still can't find a way.
For now, the only way to re-run the app is to do so.

**Comment by baegopababjo** [comment]
@Heeam-Shin 

I'm really sorry, but could you please write it on the webos site by today? I'm sending you a comment again because I really need it when submitting the results to the school comprehensive design project. I'm sure you're busy, but I sincerely ask for your help.

**Comment by Heeam-Shin** [comment]
@baegopababjo,

I understand your situation. Is it okay to publish this post at 7:00 PM?

**Comment by baegopababjo** [comment]
@Heeam-Shin 

YES! I think that would be perfect

**Comment by Heeam-Shin** [comment]
@baegopababjo,

I'm doing my best to edit it, but I think I'll need more time, would it be okay to push the deployment time to 8pm?

**Comment by Heeam-Shin** [comment]
@baegopababjo,

The editing has been completed. Could you review the document?

\+ 
The topic and title overlap with another team's post that was deployed first, so a title change is inevitable.

**Review by Heeam-Shin — APPROVED** [review]

**Comment by baegopababjo** [comment]
@Heeam-Shin 

Yes. As you said, I changed the subject name. I think the document is very well written. Thank you so much.

**Comment by Heeam-Shin** [comment]
@baegopababjo,

For a quick fix, I manually-reflected your changes to my branch and then used forced-push.

**Comment by Heeam-Shin** [comment]
Something is messed by my forced-push.... I trying to figure out how to solve it.

**Comment by Heeam-Shin** [comment]
@baegopababjo,

I apologize for any inconvenience caused by my mistake.

I've moved your work to 'reflect-pr9-branch', could you please fork this branch and create a pull request to develop branch again?

**Comment by baegopababjo** [comment]
@Heeam-Shin 
I think it's because of the modification of the email at the end.

**Comment by baegopababjo** [comment]
@Heeam-Shin 

Ok, I got it!

**Comment by baegopababjo** [comment]
@Heeam-Shin 
Currently, I am trying to delete the existing fork, make a new fork, and then make a pull request to the develop branch, but the error message below is displayed.

"Pull request creation failed. Validation failed: must be a collaborator"

Did I do anything wrong?

**Comment by Heeam-Shin** [comment]
@baegopababjo,

Could you re-create a pull request to the main branch?

**Comment by baegopababjo** [comment]
@Heeam-Shin 

My team member is making a new pull request.

**Comment by Heeam-Shin** [comment]
Okay, I checked it. I'll publish the post using that pr.

**Comment by Heeam-Shin** [comment]
This pull request goes before #14.

**Pull request closed without merging**
