### PR TITLE
Signage solution

### PR DESCRIPTION
**Pull request by noFlowWater**
I would like to incorporate this guide post about the results of our capstone design project into the website. 
Please review our [2023-12-19-face-certificate-kiosk-using-webos.md](https://github.com/noFlowWater/website/blob/signage_solution/content/en/samples/posts/2023-12-19-face-certification-kiosk-using-webos.md) and [other related files.](https://github.com/webosose/website/pull/11/files)

> Note: [our project repository](https://github.com/noFlowWater/signage_solution?tab=readme-ov-file)

### CODE REVIEW

**Comment by Heeam-Shin** [comment]
Hi @noFlowWater , thanks for your contribution.

- Your pull request (PR) is in draft status. When you finish your job, please click 'Ready for review', and then I'll review your PR. (Refer to the ① in the below screenshot.)
- You can preview your website using the 'Details' in this pull request. (Refer to the ② in the below screenshot.)

image

If you have any other questions, feel free to let me know. Thanks! :)

----

### Tips

You can build your own preview on your computer. This makes you edit markdown much easier. 

The steps are as follows:

1.  Go to [Hugo Project](https://github.com/gohugoio/hugo) and download `hugo_extended_xxx` in the **Releases** (Version: [v0.111.1](https://github.com/gohugoio/hugo/releases/tag/v0.111.1))
2. Extract the download `.zip` file.
3. (Recommended) Add `hugo.exe` to environment variables.
4. Go to the root folder of the website, and execute the `hugo` as follows:
     ```
     hugo server -F
     ```
    Then the build process will be started. If you succeed, you can see `Press Ctrl+C to stop` at the bottom.
    ```
    ...
    
    Serving pages from memory
    Running in Fast Render Mode. For full rebuilds on change: hugo server --disableFastRender
    Web Server is available at //localhost:1313/ (bind address 127.0.0.1)
    Press Ctrl+C to stop
    ```
5. Once the build process is done, open any browser and go to `localhost:1313`

**Comment by Heeam-Shin** [comment]
@noFlowWater,

Please update the description for this pull request. This helps others understand what this pull request is about.

**Comment by noFlowWater** [comment]
> Collaborator

I've updated the related matter.
If there's anything else that needs to be fixed, please let me know!

**Comment by Heeam-Shin** [comment]
@noFlowWater,

I'm trying to follow your instructions. Are there any tips to increase the success rate of facial recognition?

**Comment by noFlowWater** [comment]
@Heeam-Shin 
During development, there was a time when the parameter values related to face recognition were adjusted ( minSize=(210,210) ),

```python
def face_detector(img, size = 0.5):
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    faces = face_classifier.detectMultiScale(gray,1.3,5,minSize=(210,210)) #얼굴 최소 크기. 이것보다 작으면 무시

    if faces is():
        return img,[]

    for(x,y,w,h) in faces:
        cv2.rectangle(img, (x,y),(x+w,y+h),(0,255,255),2)
        roi = img[y:y+h, x:x+w]
        roi = cv2.resize(roi, (200,200))

    return img,roi
```

Before setting the minimum size for recognizing a face, we find a problem of recognizing a face even for a small object other than a face,
The minimum size limit has been increased.

Make sure your face comes out big on the cam,
If your eyebrows are visible and your face is shaded well, it will be recognized well.

Nevertheless, if you have facial recognition problems,

Refresh the page, or,
Try running the application again

**Comment by Heeam-Shin** [comment]
@noFlowWater,

I've reviewed your PR and there seems to be no issues with the content. I would like to suggest the following for better documentation:

- In the `./deploy.sh`, it would be nice to add a comment to the `ares-* -d` option to replace its argument appropriately.

### Suspected Errors

- When I tried with Python 3.11, I got an error during the Flask execution phase. I'm not exactly sure if this is due to Python, but if it is, I think we should add a warning note to use version 3.9.

### What's Next

1. From now on, I'll be adding a few commits to this PR to fix grammar and documentation style. 
2. After I complete the steps, I'll request you to review the revised version. 
3. If there are no issues after review, I'll merge this PR.

**Comment by Heeam-Shin** [comment]
@noFlowWater, 

I've finished the review, and I restructured the document a lot. Please check the revised document using the preview website (refer to the guide in the previous comment).

If you think the revised version is good, let me know, and then I'll merge the pull request.

--- 

One thing needs to be confirmed. In the original document, the term 'cosin jaccard similarity` is used. However, from what I can find, Cosine similarity and Jaccard similarity are different concepts, and it appears that this project used Jaccard. So, I changed the sentence as follows. If this change is wrong, please let me know. 

### Original 

**Recruiting Similar Users**: Using cosin jaccard similarity as a criterion, selecting the top N users with the highest similarity.

### Revised

**Selecting Simiilar Users**: Using Jaccard similarity, selecting the top N users with the highest similarity.

**Comment by noFlowWater** [comment]
@Heeam-Shin 

> In the ./deploy.sh, it would be nice to add a comment to the ares-* -d option to replace its argument appropriately.

Regarding the issue
Previously, all the parameters were hardcoded
We modified `deploy.sh` and [GET START guide (`README.md`)](https://github.com/noFlowWater/signage_solution/blob/main/react_signage/README.md) in the react directory to receive and process parameters.

> When I tried with Python 3.11, I got an error during the Flask execution phase. I'm not exactly sure if this is due to Python, but if it is, I think we should add a warning note to use version 3.9.

The issue is also,
Added a command to the [GET START guide (`README.md`)](https://github.com/noFlowWater/signage_solution/blob/main/flask/README.md) in the flask directory.

please check the modified version of GET START guide

> One thing needs to be confirmed. In the original document, the term 'cosin jaccard similarity` is used. However, from what I can find, Cosine similarity and Jaccard similarity are different concepts, and it appears that this project used Jaccard. So, I changed the sentence as follows. If this change is wrong, please let me know.

> Original
> Recruiting Similar Users: Using cosin jaccard similarity as a criterion, selecting the top N users with the highest similarity.

> Revised
> Selecting Simiilar Users: Using Jaccard similarity, selecting the top N users with the highest similarity.

The issue of similarity algorithms seems to be our mistake.
Thank you for correcting it :)

> If you think the revised version is good, let me know, and then I'll merge the pull request.

Absolutely, the revised version looks great.!<br/>
If you find my modifications satisfactory, you can proceed with merging the pull request.

**Comment by noFlowWater** [comment]
I missed adding the socket.io badge.
I've now included it as shown below, is that okay?
스크린샷 2023-12-21 오전 11 42 11

**Comment by Heeam-Shin** [comment]
@noFlowWater ,

It looks good. If there are no other changes, I'll publish this post at 14:00 today.

**Review by Heeam-Shin — APPROVED** [review]

**Comment by Heeam-Shin** [comment]
@noFlowWater ,

Could you re-make the pull request into `develop`? I forgot to merge the pull request as 'squash'.

**Comment by noFlowWater** [comment]
@Heeam-Shin 

I just sent you a new PR request.!

**Comment by Heeam-Shin** [comment]
> @Heeam-Shin 
> 
> 
> 
> I just sent you a new PR request.!

Thanks! After I finished a meeting, I'll check the pull request. Sorry for bothering you.

**Comment by noFlowWater** [comment]
@Heeam-Shin 

Sure, take your time with the meeting. I appreciate your effort in checking the pull request. No worries about the bother, happy to help!

**Pull request merged**
